app/baiter/victims/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SelectField, FloatField
from wtforms.validators import InputRequired
from baiter.models import classes


class VictimForm(FlaskForm):
    name = StringField('Name')
    server = StringField('Server')
    wow_class = SelectField(
        'Class',
        validators=[InputRequired()],
        choices=[(c, v['pretty_name']) for c, v in classes.items()]
    )
    x_coord = FloatField('X Coordinate')
    y_coord = FloatField('Y Coordinate')

app/baiter/main.py
from flask import (
    redirect,
    request,
    render_template,
    Blueprint,
    url_for
)


from flask_login import login_required, login_user, current_user, logout_user


from baiter import discord, db
from baiter.models import User, Victim
from baiter.auth import CALLBACK_ROUTE
from baiter.models import classes


main_bp = Blueprint('main_bp', __name__)


@main_bp.route('/')
@main_bp.route('/home')
def home():
    """
    TODO: see overview of kill statistics/list of kills if logged in?
    """
    if current_user.is_authenticated:
        victims = Victim.query.order_by(Victim.added.desc())
        return render_template('victims.html', victims=victims, classes=classes)
    else:
        return render_template('home.html', oauth_url=discord.oauth_url)


@main_bp.route(CALLBACK_ROUTE)
def callback():
    code = request.args['code']
    token = discord.access_token(code)
    current_user = discord.get_current_user(token)

    user = User.query.filter_by(discord_id=current_user['id']).first()
    if not user:
        user = User(
            discord_id=current_user['id'],
            username=current_user['username']
        )
        db.session.add(user)
        db.session.commit()

    login_user(user)
    return redirect(url_for('main_bp.home'))


@main_bp.route('/logout')
@login_required
def logout():
    logout_user()
    # flash('You have been logged out.')
    return redirect(url_for('main_bp.home'))

# @main_bp.route("/crater", methods=["GET", "POST"])
# def add_victim():
#     if request.method == "POST":
#         class_choice = request.form["class_choice"]
#         location = request.form["location"]
#         # Do something with the form data
#         return "Class: {} Location: {}".format(class_choice, location)
#     return render_template("add_victim.html", classes=classes)

app/baiter/victims/routes.py
from datetime import datetime
from flask import (render_template, url_for, flash,
                   redirect, abort, Blueprint)
from flask_login import current_user, login_required
from baiter import db
from baiter.models import Victim, classes, l_classes
from baiter.victims.forms import VictimForm


victims = Blueprint('victims', __name__)


@victims.route("/victims/new", methods=['GET', 'POST'])
@login_required
def new_victim():
    form = VictimForm()
    if form.validate_on_submit():
        victim = Victim(
            name=form.name.data,
            server=form.server.data,
            wow_class=form.wow_class.data,
            x_coord=form.x_coord.data,
            y_coord=form.y_coord.data,
            user_id=current_user.id,
            added=datetime.utcnow(),
        )
        db.session.add(victim)
        db.session.commit()
        # flash('Your victim has been created!', 'success')
        return redirect(url_for('main_bp.home'))
    return render_template('create_victim.html', title='New Victim', form=form, classes=classes, l_classes=l_classes)


@victims.route('/victims/delete/<int:id>', methods=['POST'])
@login_required
def delete_victim(id):
    victim = Victim.query.get(id)
    if victim.user_id != current_user.id:
        abort(403)  # Forbidden
    db.session.delete(victim)
    db.session.commit()
    flash('Victim deleted successfully.', 'success')
    return redirect(url_for('main_bp.home'))

app/baiter/templates/add_victim.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="static/style.css">
  <title>Crater Baiter {{app_version}}</title>
</head>
<body class="bg-black">
  <main>
    <div class="main-page-wrapper container flow text-white">
      <h1 class="ff-heading fs-900">Crater Baiter {{app_version}}</h1>
      <form action="/" method="post" class="flow">
          <label class="fs-500 ff-heading fw-700" for="class_choice">Choose a class:</label>
          <div class="class-choice">
            {% for class in classes %}
              {% set name = class.pretty_name %}
              {% set css = class.css %}
              <div class="class-item">
                <input type="radio" id="{{ name|lower }}" name="class_choice" value="{{ name|lower }}">
                <label for="{{ name|lower }}">
                  <span class="class-name {{ css|lower }}">{{ name }}</span>
                </label>
              </div>
            {% endfor %}
          </div>
        <div class="flow">
          <label for="location">Mark your location in Dalaran Crater:</label>
          <input type="text" id="location" name="location" readonly>
          <button type="submit" class="wow-button bg-wow-red text-white fw-700"> Mark </button>
        </div>

        <img src="{{url_for('static', filename='crater.png')}}" onclick="getCursorPosition(event)">
      </form>
    </div>
  </main>
  
  <script>
    function getCursorPosition(e) {
      var x = e.clientX;
      var y = e.clientY;
      document.getElementById("location").value = x + ", " + y;
    }
  </script>
</body>
</html>

app/baiter/templates/create_victim.html
{% extends "layout.html" %}
{% block content %}

<main class="px-3">
  <h1>Create New Victim</h1>
  <form method="POST" action="{{ url_for('victims.new_victim') }}">
    {{ form.csrf_token }}
css
Copy code
<div class="form-group">
  {{ form.name.label }}
  {{ form.name(class="form-control") }}
  {% for error in form.name.errors %}
    <span class="text-danger">{{ error }}</span>
  {% endfor %}
</div>

<div class="form-group">
  {{ form.server.label }}
  {{ form.server(class="form-control") }}
  {% for error in form.server.errors %}
    <span class="text-danger">{{ error }}</span>
  {% endfor %}
</div>

<style>
  {% for wow_class, feats in classes.items() %}
  .button{{wow_class}}
</style>
<div class="form-group">
  
  <div class="row">
    <div class="col-md-6">
    {% set selected_class = form.wow_class.data %}
    {% for wow_class in l_classes[:5] %}
      <button type="button" class="btn {{ 'btn-outline-danger' if selected_class != wow_class else 'btn-danger' }}" name="{{ classes[wow_class]['pretty_name'] }}" value="{{ wow_class }}" style="border-color: {{ classes[wow_class]['color'] }}; color: {{ classes[wow_class]['color'] }};">{{ classes[wow_class]['pretty_name'] }}</button>
    {% endfor %}
  </div>
  <div>
    {% for wow_class in l_classes[5:] %}
      <button type="button" class="btn {{ 'btn-outline-danger' if selected_class != wow_class else 'btn-danger' }}" name="{{ classes[wow_class]['pretty_name'] }}" value="{{ wow_class }}" style="border-color: {{ classes[wow_class]['color']  }}; color: {{ classes[wow_class]['color'] }};">{{ classes[wow_class]['pretty_name'] }}</button>
    {% endfor %}
  </div>
</div>

<div class="form-group">
  {{ form.x_coord.label }}
  {{ form.x_coord(class="form-control") }}
  {% for error in form.x_coord.errors %}
    <span class="text-danger">{{ error }}</span>
  {% endfor %}
</div>

<div class="form-group">
  {{ form.y_coord.label }}
  {{ form.y_coord(class="form-control") }}
  {% for error in form.y_coord.errors %}
    <span class="text-danger">{{ error }}</span>
  {% endfor %}
</div>

<button type="submit" class="btn btn-primary">Create</button>
  </form>
</main>
{% endblock content %}

app/baiter/templates/home.html
{% extends "layout.html" %}
{% block content %}
<main class="px-3">
    <h1>Track your sacrifices to Dalaran!</h1>
    <p class="lead">With Crater Baiter, you can now keep track of your mischiefs created using mage portals to old Dalaran!</p>
  <p class="lead">
    <a href="{{ oauth_url }}" class="btn btn-lg btn-light fw-bold border-white bg-white">Discord Login</a>
  </p>
</main>
{% endblock content %}

app/baiter/templates/layout.html
<!doctype html>
<html lang="en" class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.108.0">
    <title>Crater Baiter - v0.1</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/cover/">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="static/crater_baiter_v1.png" sizes="180x180" type="image/png">
<link rel="shortcut icon" href="/static/crater_baiter_v1.png" sizes="32x32 16x16" type="image/png">
<link rel="icon" href="/static/crater_baiter_v1.png">
<meta name="theme-color" content="#712cf9">
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }


      .deathknight {
          color: #C41F3B;
      }

      .demonhunter {
          color: #A330C9;
      }

      .druid {
          color: #FF7D0A;
      }

      .hunter {
          color: #ABD473;
      }

      .mage {
          color: #69CCF0;
      }

      .monk {
          color: #00FF96;
      }

      .paladin {
          color: #F58CBA;
      }

      .priest {
          color: #FFFFFF;
      }

      .rogue {
          color: #FFF569;
      }

      .shaman {
          color: #0070DE;
      }

      .warlock {
          color: #9482C9;
      }

      .warrior {
          color: #C79C6E;
      }

      .evoker {
          color: #008149;
      }

      form button[type="submit"].d-none {
        display: none;
      }
      
      form button[type="submit"] {
        margin-right: 0.5rem;
      }
      
      form button[type="submit"] .fa-trash {
        margin-left: 0.5rem;
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="cover.css" rel="stylesheet">
  </head>
  <body class="d-flex h-100 text-center text-bg-dark">
    
    
<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  
    <header class="mb-auto">
    <div>
      <h3 class="float-md-start mb-0">Crater Baiter</h3>
      {% if current_user.is_authenticated %}
      <nav class="nav nav-masthead justify-content-center float-md-end">
        <a class="nav-link fw-bold py-1 px-0" href="{{ url_for('main_bp.logout') }}">Log Out</a>
      </nav>
      {% endif %}
    </div>
  </header>
  {% block content %}{% endblock %}
  

  <footer class="mt-auto text-white-50">
    <p>Made with love for mages by <a href="https://instagram.com/bjorntorage" class="text-white">ItsBarb</a>.</p>
  </footer>
</div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script>
      function showConfirmDialog(id) {
        var deleteForm = document.getElementById('delete-form-' + id);
        var deleteButton = deleteForm.querySelector('button[type="button"]');
        var confirmButton = deleteForm.querySelector('button[type="submit"]');
        
        deleteButton.classList.add('d-none');
        confirmButton.classList.remove('d-none');
      }
    </script>    
  </body>
</html>

app/baiter/templates/test.html
<h1>test!</h1>

app/baiter/templates/victims.html
{% extends "layout.html" %}
{% block content %}
<main class="px-3">
  <h1>Here are your victims, {{ current_user.username }}!</h1>
  <p class="lead"></p>  
    <table class="table table-hover table-dark">
      <thead>
        <tr>
          <th class="">Name</th>
          <th>Server</th>
          <th>Class</th>
          <th>X Coord</th>
          <th>Y Coord</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        {% for victim in victims %}
          <tr>
            <td>{{ victim.name }}</td>
            <td>{{ victim.server }}</td>
            <td class="{{ victim.wow_class }}">{{ classes[victim.wow_class]['pretty_name'] }}</td>
            <td>{{ victim.x_coord }}</td>
            <td>{{ victim.y_coord }}</td>
            <td>
              <form id="delete-form-{{ victim.id }}" action="{{ url_for('victims.delete_victim', id=victim.id) }}" method="post">
                <button type="button" class="btn btn-outline-danger" onclick="showConfirmDialog({{ victim.id }})">Delete</button>
                <button type="submit" class="btn btn-danger d-none" id="confirm-delete-{{ victim.id }}">Confirm 🗑</button>
              </form>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  <p class="lead"></p>
  <p class="lead"></p>
  <p class="lead">
    <a href="{{ url_for('victims.new_victim') }}" class="btn btn-lg btn-light fw-bold border-white bg-white">Add new victim!</a>
  </p>
</main>
{% endblock content %}